- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/pages/requests/helpers.tsx
This PR enables column autosizing following [this issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/936).
Notes:
This implementation followed the [AG Grid doc](https://www.ag-grid.com/javascript-data-grid/column-sizing/)'s recommendation of setting `columnApi.autoSizeColumns()` after the grid is ready, via onFirstDataRendered. However, `autoSizeColumns()` only gets applied to columns/rows that are visible to users. To get around this, the AG Grid doc recommends turning off its column virtualization effect, which is something that we had discussed not wanting to do since it's hacky and could affect performance.
My solution used a workaround found [here](https://github.com/ag-grid/ag-grid/issues/1692), which involves (1) squeezing …
> Enable column autosizing

- frontend/src/components/SamplesList.tsx
- frontend/src/index.scss
- frontend/src/pages/requests/helpers.tsx
This PR contains the work for [this issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/951). We're combining the Revisable and Status columns into one to make information more relevant and concise for the PMs.
Desired behavior for the combined column:
- if revisable = false, show "loading" icon
- if revisable = true and validationStatus = true, show checkmark
- if revisable = true and validationStatus = false, show warning icon
> Combine Revisable and Status columns into one

- frontend/src/components/SamplesList.tsx
- frontend/src/index.scss
- frontend/src/pages/requests/StatusToolTip.tsx
- frontend/src/pages/requests/helpers.tsx
This PR contains the work for [this Zenhub issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/955).
Checklist and notes:
- AG Grid's Tooltip API doesn't currently allow for a consistent tooltip. To get around this, I set the time after which the tooltip hides from 10s (default) to 60s. This should suffice for reading the error reports, but if/when we need to make it consistent, we can either override the API or write a popup/modal component.
- Make the validation report text wrap on white space only. Previously, the text wrapping sometimes broke up words
- General cleanup/refactoring of the code that reads the validation report text and processes it to be displayed by AG Grid
- Convert the validation report's texts from lower case …
> General cleanup, polishing of current work

- frontend/src/components/SamplesList.tsx
- frontend/src/pages/requests/StatusToolTip.tsx
- frontend/src/pages/requests/helpers.tsx
This PR contains the bug fix for [this Zenhub issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/962). 
This bug causes a "white screen of death" when viewing samples that are missing a validation status and is resulted from the frontend (`SamplesList.tsx`) trying to access the `validationStatus` field. The console's error message is `caught TypeError: Cannot read properties of undefined (reading 'validationStatus')`.
With this fix, AG Grid rows of SampleMetadata that are missing Status will also show a warning icon that shows the tooltip window below upon hovering:
> Allow dashboard to handle SampleMetadata nodes that are missing Status

- frontend/src/pages/requests/helpers.tsx
This PR contains the work for [this Zenhub issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/932), which involves making the Samples view's editable columns and non-editable columns more discernible.
I offered the PMs a few UI options [here](https://mskcmo.slack.com/archives/C01HQ1ZAUUU/p1685641794260129), and all three who responded voted for the lock icon.
This lock icon was added by modifying the default column header component. The majority of the HTML code injected is the template for AG Grid's default header (found [here](https://www.ag-grid.com/react-data-grid/column-headers/)), and the lock icon is added via the `svg` element. (As in, if we remove the `svg` element from the custom header component params, the headers will …
> Add a lock icon to headings of non-editable cells

- frontend/src/pages/requests/helpers.tsx
[Related Zenhub issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/971)
Temporarily disabling sorting for select data fields until we enable their sorting functionality as part of [this issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/960). Also permanently disabled sorting for the `View` column on both pages since it's not a data column.
> Temporarily disable sorting for 'nested' data fields

- frontend/src/components/SamplesList.tsx
[Related ZenHub issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/978).
This PR introduces bulk searching for both the standalone Samples page and the Samples modal within the Requests and Patients pages. 
Note that table data on the Requests and Patients pages are rendered server-side, while those on the Samples view are rendered client-side. AG Grid has different loading animations for each rendering style (see images below). It doesn't look like we can use the same loading animation for all these pages, unless they use the same rendering style.
Samples page's loading:
Requests page's loading:
> Implement bulk searching for Samples view

- frontend/src/pages/patients/PatientsPage.tsx
Currently, when user enters an invalid input during an MRN/PHI-enabled search and initiate Search, the web page will return a blank screen. ("Invalid" here is defined as a Patient ID that doesn't exist in the CRDB Oracle table, such as "loremipsum".) 
This PR modifies the function that fetches data from the CRDB (`fetchPatientIdsTriplets()`) so that it only returns non-null data.
@ao508 The [current SMILE dashboard in dev](https://smile-dev.mskcc.org:3006/patients) reflects this code change for you to test it live.
> Handle invalid inputs for MRN search

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/shared/tableElements.tsx
**Context:**
- The `RecordsList` component currently renders the (1) Requests and (2) Patients pages
- The `SamplesList` component currently renders (1) the Samples page and (2) the Samples view modal on the Requests and Patients pages
- This ticket's original goal is to combine these components into one
-----
**TL;DR: Instead of combining these two components into one, I recommend that we simply remove the duplicated codes between them into shared codes for now.**
Although these components render similar-looking UIs, their functionalities have some fundamental differences (examples at the end). Additionally, we will add HERA data to the SMILE dashboard in the coming sprints, and we don't know how exactly HERA data will be displayed for users yet.
If we were to combine `RecordsList` and …
> Refactor RecordsList and SamplesList

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/generated/graphql.ts
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql.schema.json
- graphql/operations.graphql
Screenshots of the new billing fields in the Cohort and Cohort Sample views:
> Show billing-related fields on the Cohort and Cohort Sample views

- frontend/package.json
- frontend/src/shared/helpers.tsx
- yarn.lock
These changes make a couple assumptions:
1. The delivery date referenced for calculating the embargo date will always be available (never null)
2. The delivery date parsed will always be valid and can be parsed
3. We can always rely on using a substring of the calculated embargo date ISO string to get the YYYY-MM-DD format. 
~~**Why not use an actual date formatter?**~~
~~I didn't want to introduce yet another new package/dependency to the project.~~
Switched to using an actual date formatter
> Add embargo date to cohort samples table

- frontend/package.json
- yarn.lock
I've noticed that we have multiple versions of `moment` installed as seen [here](https://github.com/mskcc/smile-dashboard/commit/6e6978b8de8d71939d4889df5bb21b1769e147a4#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR9879-R9888). This might be a cause of the "No overload matches this call" frontend error.
In this PR, I'm reverting the frontend package specifications back to their previous state. We already have `moment` installed because it's a dependency of the `apollo` package. (A dependency of a dependency won't show up in `package.json`.)
> Fix dependency issue

- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql.schema.json
- graphql/operations.graphql
These changes surface additional fields in the Cohort Samples table.
Fields surfaced:
- custodianInformation (as Data Custodian)
- accessLevel (as Access Level)
These changes also included related updates to the graphql data schema
> Surface additional fields in Cohort Samples table

- frontend/src/components/SamplesList.tsx
- frontend/src/components/UpdateModal.tsx
- frontend/src/generated/graphql.ts
- frontend/src/index.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/neo4j.ts
- graphql.schema.json
- graphql/operations.graphql
This PR implements the optimistic update behavior for the Cohort Sample update workflow.
Before:
https://github.com/mskcc/smile-dashboard/assets/86090707/9e6ea35c-f0ed-4e37-8869-68ed81b2d180
After:
https://github.com/mskcc/smile-dashboard/assets/86090707/a7180b13-6565-4aa2-aeac-384c8b1813ce
> Implement optimistic response for Tempo field updates

- frontend/src/generated/graphql.ts
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql.schema.json
This PR addresses mskcc/smile-server#1124 and mskcc/smile-server#1110:
For mskcc/smile-server#1124, this PR enables fuzzy search for `endUsers` and `pmUsers` fields for **both** single-value and bulk searches.
https://github.com/mskcc/smile-dashboard/assets/86090707/11f0591f-9352-41c4-b678-160e28e2c53f
Note that mskcc/smile-server#1110 has been unintentionally handled by a previous PR. Demo: [this page](https://smile-dev.mskcc.org:3006/cohorts/CCS_PPPQQQQ_2) doesn't break even though the sample has no Tempo events.
> Enable searching for `endUsers` and `pmUsers` fields on Cohorts page

- frontend/src/App.tsx
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/schemas/neo4j.ts
This PR adds additional Tempo-related fields to the table on Samples page. Note that while these Tempo fields are editable on the Cohort Sample view, these fields are read-only on the Samples page.
https://github.com/mskcc/smile-dashboard/assets/86090707/12306735-c104-4113-bcfb-54255c059b0a
> Add Tempo fields to the Samples page

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/components/InfoToolTip.tsx
- frontend/src/shared/helpers.tsx
- frontend/src/shared/tableElements.tsx
This PR adds tabs to the general Samples page that filter columns by SampleMetadata vs. Tempo, making it easier to navigate these fields.
These tabs work in tandem with the following:
- search bar
- column-level filter (e.g. of the "Billed" column)
- exporting file
https://github.com/mskcc/smile-dashboard/assets/86090707/3694249d-0371-4708-9b45-8fdeb7fb7b28
> Filter SampleMetadata and Tempo fields on Samples page via tabs

- frontend/src/components/RecordsList.tsx
- frontend/src/generated/graphql.ts
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/neo4j.ts
- graphql.schema.json
- graphql/operations.graphql
For [card #1211](https://github.com/mskcc/smile-server/issues/1211).
This PR "flattens" the GraphQL-queried data from Neo4j, bringing nested fields to the root level.
<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>
```gql
node {
field1
hasChildNode {
field2
field3
}
}
```
</td>
<td>
```gql
node {        
field1        
field2        
field3        
}
```
</td>
</tr>
</table>
This "flattening" is done by adding these fields to the Neo4j schema, then writing resolvers so that the Apollo Client knows how to return data for these fields.
Pros:
- Right now, we’re unable to perform sorting of nested fields as that isn't natively supported by GraphQL[^1]. Having custom resolvers for these nested fields allow us to write logic to handle sorting in a future ticket.
- Moving the …
> Flatten data queried to SSRM AG Grid tables

- frontend/src/components/RecordsList.tsx
- frontend/src/generated/graphql.ts
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/neo4j.ts
- graphql.schema.json
- graphql/operations.graphql
This PR is a superset of #140, so we can either merge them both in order or just merge this one.
This PR introduces the following changes:
- Tab name updates in Samples page
- Show Import Date in Requests view
- Auto-sort the initial load of Requests view by Import Date
- Auto-sort the initial load of Cohorts view by Initial Cohort Delivery Date
Note that this PR only applies sorting to the initial load of the aforementioned views. The ability to manually sort fields will be introduced in a future PR for card [#1152](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1152).
> Auto sort the Requests and Cohorts views

- frontend/src/components/RecordsList.tsx
- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/neo4j.ts
- graphql.schema.json
For card [#1152](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1152).
This PR enables users to sort any of the fields in Requests, Patients, and Cohorts views, including nested fields.
Demo on sorting Request columns:
https://github.com/user-attachments/assets/c0986e09-0c08-47df-8329-d42f88c4f4b6
> Enable sorting for all columns in Requests, Patients, and Cohorts views

- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/package.json
- graphql-server/src/env/application.properties.EXAMPLE
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/neo4j.ts
- graphql-server/src/utils/constants.ts
- graphql-server/src/utils/oncotree.ts
- graphql-server/src/utils/servers.ts
- graphql.schema.json
- graphql/operations.graphql
- yarn.lock
PR for card [#1232](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1232).
This PR adds `cancerType` and `cancerTypeDetailed` fields corresponding to `oncotreeCode` values to views with SampleMetadata data.
Data for these fields are initially fetched from the Oncotree API's candidate release upon the GraphQL server startup, and it's then cached with a duration of 1 day (matches cBioPortal's setting). When the GraphQL custom resolver encounters a new `oncotreeCode` that isn't in the cache, it will refetch from the Oncotree API and refresh the cache.
Old `oncotreeCode` values (like "HIST") with no matching data from the Oncotree API have `cancerType` and `cancerTypeDetailed` fields as "N/A", along with a tooltip describing the issue. …
> Add cached Oncotree data to Samples views

- frontend/src/components/SamplesList.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- graphql-server/package.json
- graphql-server/src/schemas/neo4j.ts
- graphql-server/src/utils/dataloader.ts
- graphql-server/src/utils/flattening.ts
- graphql-server/src/utils/ogm.ts
- graphql-server/src/utils/servers.ts
For card [#1225](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1225).
This PR implements the following changes:
- Automatically sort samples query results by importDate in descending order
- Improve performance of the React frontend by removing an unnecessary re-render on the Samples page
- Improve performance of the GraphQL server by batching child queries of the SamplesList query, removing an extra trip to the database
The performance improvements reduced the initial loading time by 2x, but it still takes a while; I'm seeing 1m30s - 2m.
In parallel, we'll add a new environment variable `NODE_OPTIONS="--max-old-space-size=16384"`. This increases the heap memory space available to the Node.js runtime from 4GB to 16GB. Fetching all …
> Automatically sort samples query results by importDate

- graphql-server/src/utils/flattening.ts
These changes resolve the CMO patient ID from a given Patient's aliases instead of from a patient's sample metadata > cmoPatientId.
Current behavior:
Expected behavior / behavior after changes from this PR:
> Resolve CMO Patient ID from PatientAlias

- graphql-server/src/utils/flattening.ts
Fixes issue where records in the Patient view weren't showing 12-245 Part A/C consent statuses even though they exist in the database. 
Current behavior:
Expected behavior / behavior after changes from PR:
> Fix displayed consent part a/c status on patient table

- frontend/src/components/DownloadModal.tsx
- frontend/src/components/SamplesList.tsx
- graphql-server/src/schemas/neo4j.ts
- graphql-server/src/utils/dataloader.ts
- graphql-server/src/utils/ogm.ts
- graphql-server/src/utils/oncotree.ts
For [card 1237](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1237). This PR increases the max number of samples that can be exported from 500 to 5,000.
If users attempt to export more, they will see a popup asking them to either refine their search or reach out to our team.
> Increase the sample export limit

- frontend/src/shared/helpers.tsx
For [card 1268](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1268)
> Fix sample status showing warning icon when validationStatus is null

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/utils/stringBuilders.ts
For card [#1258](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1258). This PR ensures we only export visible columns when generating report from the dashboard.
The only page that is affected is the Patients page, where the exported file contains columns "Patient MRN" and "SMILE Patient ID" even though they're hidden and user is not in PHI mode.
Views manually tested for dashboard's columns == exported table's columns:
> Hide hidden columns from the exported file

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/components/UpdateModal.tsx
- frontend/src/generated/graphql.ts
- frontend/src/index.tsx
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql-server/src/schemas/neo4j.ts
- graphql-server/src/utils/servers.ts
- graphql.schema.json
- graphql/operations.graphql
For card [#1280](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1280). This PR also addresses the following bugs:
TODOs for a future PR:
> Re-enable editing for the new Samples query

- frontend/src/components/AlertModal.tsx
- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/components/UpdateModal.tsx
- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- frontend/src/shared/tableElements.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql-server/src/schemas/oracle.ts
- graphql-server/src/utils/servers.ts
- graphql.schema.json
- graphql/operations.graphql
This PR transitions the Sample views' AG Grid [row model](https://www.ag-grid.com/javascript-data-grid/row-models/) from Client-Side to Server-Side, allowing the grid to lazy-load the data as the user scrolls down.
[#1291](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1291)
> Implement infinite scrolling for the Sample views

- frontend/src/components/NewRecordsList.tsx
- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/generated/graphql.ts
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/shared/helpers.tsx
- frontend/src/shared/tableElements.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql-server/src/schemas/oracle.ts
- graphql.schema.json
- graphql/operations.graphql
For card [#1292](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1292). This PR migrates the Patients page from OGM to using a direct Neo4j query, improving the performance of the page.
> Migrate Patients page to using a direct Neo4j query

- frontend/src/shared/helpers.tsx
- frontend/src/utils/stringBuilders.ts
- graphql-server/src/schemas/custom.ts
This PR corresponds with card [#1229](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1229) and adds column filters to the following columns:
- On Requests page:
- Import Date
- BIC Analysis
- CMO Request?
- On Patients page:
- 12-245 Part A
- 12-245 Part C
- On Samples page:
- Last Updated
- Initial Pipeline Run Date
- Embargo Date
- Latest BAM Complete Date
- Latest MAF Complete Date
- Latest QC Complete Date
> Enable column filters for all date and boolean columns

- .circleci/config.yml
- graphql-server/src/schemas/custom.ts
This PR adds back the missing validation info that is missing from the new samples query.
> Add missing sample validation info in the samples query

- frontend/src/components/DownloadModal.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/generated/graphql.ts
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/helpers.tsx
- frontend/src/shared/tableElements.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/queries/samples.ts
- graphql-server/src/utils/typeDefs.ts
- graphql.schema.json
- graphql/operations.graphql
This PR introduces the following:
- Ability to "Generate Phenotype files for dbGaP" on the Samples page
- `analyteType` data in the Samples query's result
[#1205](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1205)
> Add support for exporting Phenotype files for dbGaP

- frontend/src/shared/helpers.tsx
Added the following columns to the samples WES view:
- dbGap study
- historical cmo sample names
> Added columns to WES view

- frontend/src/components/RecordValidation.tsx
- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/configs/recordValidationMaps.ts
- frontend/src/generated/graphql.ts
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/components/Toolbar.tsx
- frontend/src/shared/helpers.tsx
- frontend/src/shared/tableElements.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql-server/src/schemas/queries/samples.ts
- graphql-server/src/utils/cache.ts
- graphql-server/src/utils/typeDefs.ts
- graphql.schema.json
- graphql/operations.graphql
This PR adds a new ACCESS samples tab to the Samples page.
[Add a new view on Samples page for ACCESS samples #1520](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1520) (main ticket)
[Move the info tooltip icon on the right of the search field to the left of it #1519](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1519)
[Use clearer / more user-friendly languages (e.g. “Export to TSV” instead of “Generate report”) #1518](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1518)
Signed-off-by: Quan Nguyen <86090707+qu8n@users.noreply.github.com>
> Add a new view on Samples page for ACCESS samples

- frontend/src/components/RecordValidation.tsx
- frontend/src/configs/recordValidationMaps.ts
- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/queries/requests.ts
- graphql-server/src/utils/typeDefs.ts
- graphql.schema.json
- graphql/operations.graphql
Main updates:
- groups of tolerated and critical sample errors are displayed, when applicable 
General:
- updated graphql operations and typedefs to support tolerated sample errors
- removed the general request-level sample error messages that were informative but ultimately not very helpful or actionable.
**Grouped display**
**Toggled grouped display**
**Toggled grouped display by samples**
> Display tolerated sample errors in request validation report popup

- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/queries/samples.ts
- graphql-server/src/utils/typeDefs.ts
- graphql.schema.json
- graphql/operations.graphql
- Added cohort IDs to sample records
- Cohort IDs are also searchable now on any sample view
Searching for a cohort ID on the samples page:
Search for cohort ID above matches the sample count from the Cohorts View table
@qu8n cohort IDs column displayed
> Add cohort IDs for sample records

- graphql-server/src/middlewares/configureLogging.ts
- graphql-server/src/routes/auth/callback.ts
- graphql-server/src/routes/index.ts
- graphql-server/src/utils/databricks.ts
- graphql-server/src/utils/servers.ts
- graphql-server/src/utils/session.ts
Also improve typings of the `req` object.
I couldn't find a way to see all query history of a table<sup>1</sup> so I tested this PR by temporarily printing the "warm up" queries' results when they finish running. Also confirmed that the login flow works as before.
<sup>1</sup> On Databricks, clicking a table > Insights only shows queries ran via the built-in SQL Editor. Only admins can see all tables' histories ([source](https://docs.databricks.com/aws/en/sql/user/queries/query-history#access-the-query-history-system-table)).
[#1598](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1598)
> Warm up Databricks tables upon logging in

- graphql-server/src/routes/index.ts
- graphql-server/src/utils/databricks.ts
This PR fixes the race conditions happening in #227. Because the warm-up queries are called concurrently, one query can finish and close the connection before the other query is done. To solve this, I'm having both queries run inside a single connection.
> Fix concurrency issues when warming up Databricks tables

- frontend/src/components/AlertModal.tsx
- frontend/src/components/DownloadModal.tsx
- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/generated/graphql.ts
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/components/Toolbar.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql-server/src/schemas/queries/patients.ts
- graphql-server/src/utils/databricks.ts
- graphql-server/src/utils/typeDefs.ts
- graphql.schema.json
- graphql/operations.graphql
This PR also changed the following:
* Removed the export limit that was previously 10,000 records
* By default, the export's format matches the AG Grid's table. This PR added the ability to define a custom export handler to download data in a different format
Tested:
[#1597](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1597)
> Enable exporting all anchor sequencing dates of patients

- frontend/src/components/SamplesList.tsx
Fix filter tabs on the Samples page that are no longer in sync with `SamplesList` component due to #236.
Before: changing tabs does not update the columns nor the data
https://github-production-user-asset-6210df.s3.amazonaws.com/86090707/475108904-ad278ce7-41c1-4658-b0d5-a9df700704d0.mp4
After: changing tabs update the columns and the data
https://github-production-user-asset-6210df.s3.amazonaws.com/86090707/475108917-b680b038-81b7-489f-be57-d9033cbe154d.mp4
> Fix filter tabs on the Samples page

- frontend/src/components/DataGrid.tsx
- frontend/src/index.scss
- frontend/src/pages/samples/config.tsx
- Add tooltips to select whole exome sample columns
- Move "Latest QC Complete Date" and "QC Complete Status" columns to the most right of the view (confirmed with Pav)
[#1631](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1631)
Check off items under the affected features below.
> [!NOTE]
> This PR only affects the UI and none of the functionalities below. I've tested to confirm that the tooltip appears and shows the expected text for each of the affected column header.
Confirm that these download actions return a TSV file with the expected columns and record count:
Schema changes in [typeDefs.ts](./graphql-server/src/utils/typeDefs.ts) are reflected in the following:
> Add tooltips to select whole exome sample columns

- frontend/src/App.tsx
- frontend/src/hooks/useCellChanges.ts
- Fix the buggy behavior where "editing sample A -> searching -> editing sample B -> submitting updates" only results in the update of sample B
- Side quest: fix console error React Router's console error when entering views like the Request Samples, Patient Samples, etc.
[#1580](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1580)
Check off items under the affected features below.
Confirm that these download actions return a TSV file with the expected columns and record count:
Schema changes in [typeDefs.ts](./graphql-server/src/utils/typeDefs.ts) are reflected in the following:
> Fix sample updates not fully submitted between searches
