- package.json
- src/App.tsx
- src/generated/graphql.tsx
- src/index.tsx
- src/pages/requestView/RequestSummary.tsx
- src/pages/requestView/RequestViewPage.tsx
- yarn.lock
> Add pages to dashboard app

- src/index.tsx
- src/shared/components/SmileNavBar.tsx
> Fix search bar functionality

- src/pages/recentDeliveries/RecentDeliveries.css
- src/pages/recentDeliveries/RecentDeliveriesPage.tsx
Some formatting issues are fixed now.
Refactored and consolidated some code for generating the columns and rendering table cells, etc.
> Recent deliveries table cleanup, refactoring

- src/index.tsx
- src/pages/home/HomePage.tsx
- src/pages/recentDeliveries/RecentDeliveriesPage.tsx
- src/pages/requestView/RequestSummary.tsx
todo
- get filtering to work (current workaround with click of button but not while hitting enter on keyboard while cursor in search bar)
- add editing form that renders when "editingSampelId" is not undefined
> Work in progress

- src/components/DownloadModal.tsx
- src/lib/CSVExport.ts
- src/pages/requests/RequestSummary.tsx
- src/pages/requests/RequestsPage.tsx
- src/pages/requests/helpers.tsx
> Minor changes to how files are named when exporting data

- src/pages/requests/RequestsPage.tsx
- src/pages/requests/helpers.tsx
Minor improvements to request filtering.
> Slight improvement to request filtering

- src/generated/graphql.tsx
- src/graphql/operations.graphql
- src/pages/requests/helpers.tsx
> Initial expansion of columns for request table

- src/generated/graphql.tsx
- src/graphql/operations.graphql
> Hofix samples connection to request

- .dockerignore
- Dockerfile
- README.md
- server/.dockerignore
- server/Dockerfile
- server/index.js
- src/index.tsx
> Dockerized dashboard backend and webapp

- src/pages/requests/RequestsPage.tsx
- src/pages/requests/helpers.tsx
> Fix navigation button on requests table

- src/pages/requests/RequestSummary.tsx
- src/pages/requests/RequestsPage.tsx
> Minor styling changes

- src/generated/graphql.tsx
- src/graphql/operations.graphql
- src/pages/requests/RequestSamples.tsx
- src/pages/requests/helpers.tsx
Request samples query now also only returns the latest metdata of a sample.
> Sample filter working with AgGrid

- src/generated/graphql.tsx
- src/graphql/operations.graphql
- src/pages/requests/RequestSamples.tsx
- src/pages/requests/helpers.tsx
> Add back missing sample columns

- .github/release-drafter.yml
- .github/workflows/release-management.yml
> Add release drafter

- src/index.scss
- src/index.tsx
- src/pages/advancedSearch/AdvancedSearchPage.tsx
- src/pages/home/HomePage.tsx
- src/shared/components/SmileNavBar.tsx
> Init commit for supporting advanced searches

- graphql.schema.json
- server/index.js
- server/resolvers.js
- server/yarn.lock
- src/generated/graphql.tsx
Requirements before running locally and in dev/production servers:
- run migration.cypher on neo4j db's
- backfill default status and revisable values for samples and requests
> Revisable resolver

- graphql.schema.json
- server/index.js
- src/generated/graphql.tsx
- src/graphql/operations.graphql
- src/index.tsx
- src/pages/samples/UpdateSamples.tsx
> Fixed / working custom resolver

- graphql-server/src/index.ts
> Fix NATS connection problem

- frontend/src/generated/graphql.ts
- graphql-server/src/generated/graphql.ts
- graphql/operations.graphql
Example response for `findSamplesByInputValue`:
```
{
"data": {
"samplesConnection": {
"edges": [
{
"node": {
"datasource": "igo",
"revisable": true,
"sampleCategory": "research",
"sampleClass": "Tumor",
"smileSampleId": "dccf8278-4239-49e6-9d32-b8576e19aa6f",
"hasMetadataSampleMetadata": [
{
"additionalProperties": "{\"igoRequestId\":\"11886_H\"}",
"baitSet": "IMPACT505_BAITS",
"cfDNA2dBarcode": null,
"cmoInfoIgoId": null,
"cmoPatientId": "C-U4DM5R",
"cmoSampleIdFields": "{\"naToExtract\":\"DNA\",\"normalizedPatientId\":\"MRN_REDACTED\",\"sampleType\":\"DNA\",\"recipe\":\"IMPACT505\"}",
"cmoSampleName": "C-U4DM5R-X001-d01",
"collectionYear": "2021",
"genePanel": "IMPACT505",
"igoComplete": true,
"igoRequestId": "11886_H",
"importDate": "2023-04-04",
"investigatorSampleId": …
```
> return status for every sample in list

- frontend/src/pages/requests/helpers.tsx
> warning icon validationStatus

- frontend/src/components/SamplesList.tsx
- frontend/src/index.scss
- frontend/src/pages/requests/StatusToolTip.tsx
- frontend/src/pages/requests/helpers.tsx
Updates:
- added tooltip to visualize validation reports for samples
TODO:
- make validation reports downloadable
> Support for Sample Validation Report

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
This PR contains the work for [this issue](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/973).
> Fix: sample search

- frontend/src/components/RecordsList.tsx
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/shared/helpers.tsx
> Enable filtering the Billed field on Cohorts and Cohort Samples views

- frontend/package.json
- frontend/src/components/SamplesList.tsx
- frontend/src/components/UpdateModal.tsx
- frontend/src/index.scss
- frontend/src/shared/helpers.tsx
- graphql-server/src/env/application.properties.EXAMPLE
- graphql-server/src/utils/constants.ts
- graphql-server/src/utils/servers.ts
- yarn.lock
Note that this PR rebased new changes on top of the latest in `master`.
Demo:
https://github.com/mskcc/smile-dashboard/assets/86090707/e73b9bda-9a27-456f-8a91-377d77adf49c
> Cost Center validation

- frontend/package.json
- frontend/src/components/SamplesList.tsx
- frontend/src/components/UpdateModal.tsx
- frontend/src/index.scss
- frontend/src/shared/helpers.tsx
- graphql-server/src/env/application.properties.EXAMPLE
- graphql-server/src/utils/constants.ts
- graphql-server/src/utils/servers.ts
- yarn.lock
Dev branch for cost center validation.
Main resources used when digging into this feature: 
- https://blog.ag-grid.com/user-input-validation-with-ag-grid/
- https://www.ag-grid.com/javascript-data-grid/cell-editors/
> Init commit - cost center validation (#123)

- frontend/package.json
Changes also made to the deployment `docker-compose` for this: https://github.mskcc.org/cmo/smile-deployment/pull/142/files
> Generalize webcert locations

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/shared/helpers.tsx
This PR includes the work for both tickets [#1154](https://github.com/mskcc/smile-server/issues/1154) and [#1131](https://github.com/mskcc/smile-server/issues/1131).
https://github.com/mskcc/smile-dashboard/assets/86090707/6690069e-ed59-4f4b-aea1-7733b90d5244
> Fix filtered view count and enable cohort filter by delivery date

- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/components/records.module.scss
- frontend/src/generated/graphql.ts
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/components/BreadCrumb.tsx
- frontend/src/shared/components/PageHeader.tsx
- frontend/src/shared/components/Title.tsx
- frontend/src/shared/helpers.tsx
- frontend/src/utils/stringBuilders.ts
- graphql-server/src/generated/graphql.ts
- graphql/operations.graphql
This PR addresses cards [#1222](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1222) and [#1218](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1218).
> Fix export file name and add missing Cohort Sample columns

- frontend/src/components/SamplesList.tsx
- frontend/src/components/UpdateModal.tsx
- frontend/src/pages/cohorts/CohortsPage.tsx
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/components/InfoToolTip.tsx
- frontend/src/shared/helpers.tsx
- frontend/src/shared/tableElements.tsx
- frontend/src/utils/parseSearchQueries.ts
- graphql-server/src/schemas/neo4j.ts
- graphql-server/src/utils/ogm.ts
- graphql-server/src/utils/oncotree.ts
This PR contains the ongoing work for card [#1244](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1244).
Progress tracker:
> Enable searching `cancerType` and `cancerTypeDetailed` fields in the Samples views

- README.md
- frontend/src/shared/helpers.tsx
For card [1266](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1266)
**Before**
**After**
> Hide null strings and update README

- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql.schema.json
- graphql/operations.graphql
Request Samples view:
Samples page:
Cohort Samples view:
> Show alt ID in the samples view

- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql-server/src/schemas/queries/samples.ts
- graphql.schema.json
- graphql/operations.graphql
Updates to dashboard samples view:
WES view: added sampleCategory (new), tumorOrNormal, and sampleType
Default samples view: added sampleCategory (new)
Updated graphql-generated files, etc.
> DashboardSamples updates

- frontend/src/generated/graphql.ts
- frontend/src/shared/helpers.tsx
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/queries/patients.ts
- graphql-server/src/utils/typeDefs.ts
- graphql.schema.json
- graphql/operations.graphql
Add a new column "dbGaP" to the Patients page that indicates whether that patient has a sample in a dbGaP study.
[#1510](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1510)
Signed-off-by: Quan Nguyen <86090707+qu8n@users.noreply.github.com>
> Show whether a patient exists in a dbGaP study

- graphql-server/src/schemas/custom.ts
[#987](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/987)
> Publish sample metadata updates in a single array

- graphql-server/src/schemas/custom.ts
Searching by MRNs was broken. These changes add the mapped CMO and DMP patient IDs from the patient IDs triplet search and appends them to the `searchVals` for the `dashboardPatients` query.
> Fixed MRN-based searching for patients page

- frontend/src/App.tsx
- frontend/src/components/RecordsList.tsx
- frontend/src/components/SamplesList.tsx
- frontend/src/components/UpdateModal.tsx
- frontend/src/generated/graphql.ts
- frontend/src/pages/patients/PatientsPage.tsx
- frontend/src/pages/requests/RequestsPage.tsx
- frontend/src/pages/samples/SamplesPage.tsx
- frontend/src/shared/components/Toolbar.tsx
- frontend/src/shared/helpers.tsx
- graphql-server/src/env/application.properties.EXAMPLE
- graphql-server/src/generated/graphql.ts
- graphql-server/src/schemas/custom.ts
- graphql-server/src/schemas/queries/samples.ts
- graphql-server/src/utils/cache.ts
- graphql-server/src/utils/constants.ts
- graphql-server/src/utils/databricks.ts
- graphql-server/src/utils/typeDefs.ts
- graphql.schema.json
- graphql/operations.graphql
[#1613](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1613)
> Enable PHI mode for Samples views and return Sequencing Dates

- graphql-server/src/schemas/queries/patients.ts
[#1634](https://app.zenhub.com/workspaces/smile-scrum-5fcfa28a4ccc1600165347b6/issues/gh/mskcc/smile-server/1634)
> Fix unsafe access of Anchor Sequencing Date
